MAIN_URL = 'https://stellarburgers.nomoreparties.site'

EP_REGISTER = f'{MAIN_URL}/api/auth/register'
EP_USER = f'{MAIN_URL}/api/auth/user'
EP_LOGIN = f'{MAIN_URL}/login'
EP_PROFILE = f'{MAIN_URL}/account/profile'
EP_FORGOT_PASSWORD = f'{MAIN_URL}/forgot-password'
EP_RESET_PASSWORD = f'{MAIN_URL}/reset-password'
EP_ORDER_STORY = f'{MAIN_URL}/account/order-history'
EP_ORDER_FEED = f'{MAIN_URL}/feed'
